apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: run-migrations
          image: ghcr.io/ni-cookie/diploma-backend:latest
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: admin-password
            - name: DB_DATABASE
              value: "realworld_db"
      containers:
        - name: backend
          image: ghcr.io/ni-cookie/diploma-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "fastapi_user" 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: fastapi-password
            - name: DB_DATABASE
              value: "realworld_db"
            - name: JWT_SECRET_KEY
              value: "diploma-super-secret-key-123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000